set CREDUCE_TEST_CLANG=C:\Program Files (x86)\LLVM\bin\clang.exe
set CREDUCE_TEST_CLLAUNCHER=C:\Users\Administrator\Programs\cl_launcher.exe
set CREDUCE_OPENCL_INCLUDE_PATH=

set CREDUCE_TEST_PLATFORM=0
set CREDUCE_TEST_DEVICE=0
set CREDUCE_TEST_OCLGRIND_PLATFORM=1
set CREDUCE_TEST_OCLGRIND_DEVICE=0

REM CREDUCE_TEST_DEBUG=1
REM CREDUCE_TEST_LOG=1
